//@prepros-append pages/common.js
//@prepros-append pages/inputs.js
//@prepros-append pages/index.js
//@prepros-append pages/sliders.js
//@prepros-append pages/catalog.js
//@prepros-append pages/product.js
//@prepros-append pages/compare.js
//@prepros-append pages/news.js
//@prepros-append pages/contacts.js
